### ISSUE TITLE
SyntaxError: Invalid regular expression on line 392

### ISSUE THREAD

**Issue by notme1560** [jonschlinkert/data-store#12]
https://github.com/jonschlinkert/data-store/blob/master/index.js#L392

This line:
```js
const split = str => str.split(/(?<!\\)\./).map(strip);
```
Throws an error:
```
/redacted_path/node_modules/data-store/index.js:392
const split = str => str.split(/(?<!\\)\./).map(strip);
                         ^

SyntaxError: Invalid regular expression: /(?<!\\)\./: Invalid group
    at split (/redacted_path/node_modules/data-store/index.js:392:26)
    at get (/redacted_path/node_modules/data-store/index.js:433:7)
    at Store.has (/redacted_path/node_modules/data-store/index.js:148:19)
    at /redacted_path/redacted_file.js:10:15
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/redacted_path/redacted_file.js:9:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

Changed it to:
```js
const split = str => str.split(/(?!\\)\./).map(strip);
```
And it hasn't errored yet. I don't know if my fix will break anything though.

**Comment by jonschlinkert** [comment]
> Changed it to:

A negative lookahead won't work. The node version is wrong in package.json, it should be 8.6 I think.

**Comment by notme1560** [comment]
@jonschlinkert haven't run unit tests, but it worked to temporarily fix my project.

**Comment by jonschlinkert** [comment]
I eliminated the regex negative lookbehind that caused the error. Thanks for creating the issue
